### ISSUE TITLE
Issue with compiling NNEF format

### ISSUE THREAD

**Issue by ando2097** [nanocad-lab/3pxnet#2]
After calling make MNIST=1 convert from the training directory I receive the error:

---

File "C:\Users\andre\AppData\Local\Programs\Python\Python39\lib\site-packages\nnef_tools\conversion\converter.py", line 139, in __call__
    message = self._check_conditions(op, transform)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python39\lib\site-packages\nnef_tools\conversion\converter.py", line 185, in _check_conditions
    op_attribs = self._add_default_attribs(op.attribs, transform.defaults, op_inputs, op_outputs, op.type, op.name)
AttributeError: 'NoneType' object has no attribute 'defaults'
make: *** [Makefile:17: convert] Error 1

---

I have moved the convert.py file to the training directory but after doing this I received the error: 

---

python convert.py --input-format onnx --output-format nnef --input-mode "training_data/FC_Large.onnx" --output-mode "../FC_Large.nnef"
Traceback (most recent call last):
  File "C:\Users\andre\source\repos\3pxnet\3pxnet-training\convert.py", line 15, in <module>
    from .conversion import *
ImportError: attempted relative import with no known parent package
make: *** [Makefile:17: convert] Error 1

---

I solved this by removing the relative imports and instead using the solution found at [How to import functions from other projects in Python?](https://stackoverflow.com/questions/14509192/how-to-import-functions-from-other-projects-in-python) such that the top of the file now is:

```
from os import path
import sys
sys.path.append(path.abspath('Users/andre/source/repos/NNEF-Tools'))

from nnef_tools.conversion import *
from nnef_tools.model import utils
```

I understand this may be an issue to do with the nnef-tools and not with your repository and if so please close this error.

**Comment by jianshitansuantong233** [comment]
It seems that you are installing the nnef-tools in the new way. The nnef packet we are using when developed this repository is from the branch "legacy" of NNEF-Tools repository. So I think you might have to install the packet in the same way as pointed out in branch "legacy" but not what they are showing in the master branch. Sorry for the confusion.

**Comment by ando2097** [comment]
Can I ask that you amend the readme to include this for the sake of future visitors?

**Comment by jianshitansuantong233** [comment]
Well, it's actually written in the readme in the training directory since this is mostly related to that. I will write in the top readme about this later.

**Comment by jianshitansuantong233** [comment]
Thank you for pointing it out.
