### ISSUE TITLE
Issue with running validation suite

### ISSUE THREAD

**Issue by ando2097** [nanocad-lab/3pxnet#3]
Following the readme of the inference directory I have run the command make validation and left the compiler options at the top of the makefile as default and the command has run fine. However when I run the _python scripts/runValidation.py_ command I am met with the following error for every test

Running: ./validation -f     -i 100
'.' is not recognized as an internal or external command,
operable program or batch file.

**Comment by wromaszkan** [comment]
Hey,

What OS and shell are you running it from?

**Comment by ando2097** [comment]
I am running on windows 10 from the vscode powershell

**Comment by wromaszkan** [comment]
Ok, we haven't tested the library on Windows/VSCode, and I can't reproduce this issue on Linux. We'll try to reproduce your setup to see what's going on.

**Comment by wromaszkan** [comment]
Hey @ando2097, can you let me know exactly what versions of GCC and Make are you using, and any VSCode extensions related to those? Thanks.

**Comment by ando2097** [comment]
GNU Make 4.3
gcc (MinGW.org GCC-6.3.0-1) 6.3.0
no vscode extensions related to either

**Comment by wromaszkan** [comment]
Hi,

Thank you for your patience. You should be able to solve this by changing line 63 in runValidation.py from:

`                  cmdString = "./validation" + layer + ob + bn + sp + " -i " + str(self.iters)`

To:

`                  cmdString = "validation" + layer + ob + bn + sp + " -i " + str(self.iters)`

We will not be fixing this in the repository, as we are not planning on officially supporting Windows-based setups. Apologies for the inconvenience. Please let me know if that fixes the issue.
